-- MySQL Script generated by MySQL Workbench
-- Tue Feb 19 02:33:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MSPR_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MSPR_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MSPR_DB` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `MSPR_DB` ;

-- -----------------------------------------------------
-- Table `MSPR_DB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MSPR_DB`.`AGENT` (
  `ID_AGENT` INT(4) NOT NULL,
  `LASTNAME` VARCHAR(30) NULL,
  `FIRSTNAME` VARCHAR(30) NULL,
  `EMAIL` VARCHAR(30) NULL,
  `PHONENUMBER` INT(10) NULL,
  -- `PHOTO` VARCHAR(255) NULL,
  PRIMARY KEY (`idAgent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MSPR_DB`.`MATERIAL` (
  `ID_MATERIAL` INT(4) NOT NULL,
  `LABEL` VARCHAR(30) NULL,
  `MAXAMOUNT` INT(10) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MSPR_DB`.`Emprunter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MSPR_DB`.`BORROWING` (
  `ID_AGENT` INT NULL,
  `ID_MATERIAL` VARCHAR(45) NULL,
  INDEX `ID_USER_idx` (`ID_AGENT` ASC),
  CONSTRAINT `ID_AGENT`
    FOREIGN KEY (`ID_AGENT`)
    REFERENCES `MSPR_DB`.`AGENT` (`ID_AGENT`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT,
  CONSTRAINT `ID_MATERIAL`
    FOREIGN KEY (`ID_MATERIAL`)
    REFERENCES `MSPR_DB`.`MATERIAL` (`ID_MATERIAL`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

USE `MSPR_DB` ;

-- -----------------------------------------------------
-- Placeholder table for view `MSPR_DB`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MSPR_DB`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `MSPR_DB`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MSPR_DB`.`view1`;
USE `MSPR_DB`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
